### PR TITLE
PY-Chang turns in hw0 (attempt 1)

### PR DESCRIPTION
**Pull request by PY-Chang**
---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Review by yungyuc — CHANGES_REQUESTED** [review]
You wrongly included my change (set) https://github.com/yungyuc/nsdhw_22sp/pull/25/commits/de641f4c53763584b30a7d668ccdec9a7968598f .  Please remove it from the history (of this PR).

**Comment by PY-Chang** [comment]
> You wrongly included my change (set) [de641f4](https://github.com/yungyuc/nsdhw_22sp/commit/de641f4c53763584b30a7d668ccdec9a7968598f) . Please remove it from the history (of this PR).

Teacher, I just delete the wrongly included files, do I need to submit a PR as second attempt or not? Thx!

**Comment by yungyuc** [comment]
It is not what I asked.  The changeset https://github.com/yungyuc/nsdhw_22sp/pull/25/commits/de641f4c53763584b30a7d668ccdec9a7968598f should not appear in the history of this branch / PR.  You need something like rebase to get rid of it.

**Comment by PY-Chang** [comment]
> It is not what I asked. The changeset [de641f4](https://github.com/yungyuc/nsdhw_22sp/commit/de641f4c53763584b30a7d668ccdec9a7968598f) should not appear in the history of this branch / PR. You need something like rebase to get rid of it.

Teacher, I've used rebase to clean up the commit history.

**Review by yungyuc — APPROVED** [review]

**Pull request merged**
