### PR TITLE
Li-Pro turns in hw2

### PR DESCRIPTION
**Pull request by Li-Pro**
- [x] Question 1
- [x] Question 2

It's a bit painful for the manual include & link for pybind11 in question 2 though. Maybe a dependency `python3-dev` would be better.

---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Comment by Li-Pro** [comment]
@yungyuc it's strange. Why didn't Actions run checks against this PR 😂?
It seems to be on the right branch (hw2) and has no conflicts.

**Comment by yungyuc** [comment]
It is strange but Github Action sometimes does this.  Feel free to use an alternate PR and cross link both.

It might be OK to add `python-dev`, @q40603 how do you think?  But the painful manual configuration for the linking is intentional.  Oftentimes we do not have the luxury of having apt.  We do not live in a container world which is slow.

**Comment by Li-Pro** [comment]
But the container world is just so wonderful XD.

About `python-dev`, my implementation determines the source locations via calls to the available `python3` executable (so it works with virtual environments 🚀). But shouldn't them be configured in environment, or be provided as a Makefile input (since end-users might have multiple self-installed versions)?

**Comment by yungyuc** [comment]
> About `python-dev`, my implementation determines the source locations via calls to the available `python3` executable (so it works with virtual environments 🚀). But shouldn't them be configured in environment, or be provided as a Makefile input (since end-users might have multiple self-installed versions)?

In the homework assignment, the configuration is kept as simple as possible so that the students (you) do not need to look after too many threads.

A real-world project has a wide range of options to handle the dependency.  It usually is a full time job and may not be suitable to be addressed in homework assignments.

**Pull request merged**
