### PR TITLE
Li-Pro turns in hw0

### PR DESCRIPTION
**Pull request by Li-Pro**
- [x] Run countline.py

Implement countline.py with a **dirty hack**.
It counts the number of lines by **ensuring that it is zero**. (panik)

---
A good PR should include the following parts:
- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Comment by Li-Pro** [comment]
The grading CI seems to give "NO POINT" without failing. Closing to review test.

**Comment by Li-Pro** [comment]
Fixed file permission in 2ef70a0fbe8165a44d551cd1a83cbb4d6f3fbc75. It gets full grade now.

**Comment by Li-Pro** [comment]
@yungyuc would that _dirty_ implementation be accepted 😅?
I didn't realize that we don't need to change the file though.

**Comment by yungyuc** [comment]
Your file is overly large and seems to be binary.  I will not merge it.  Please get rid of it from git history.

**Comment by Li-Pro** [comment]
@yungyuc It was not a binary, but an over-large meme in comments (GitHub does not allow that preview by default).
image

That's the core of the joke 🤣, but fine, I'll get rid of it.

**Comment by Li-Pro** [comment]
The large text block is minified.
Commits are reordered and squashed to prune large files from history. It should be compact in size now.

**Comment by yungyuc** [comment]
Thank you for the clarification.  I am not pretty sure why you are putting a joke in the example assignment.  If you are familiar with PR you do not need to use the hw0 as an exercise.  Adding a large blob in a checkin is pointless in this course.

**Pull request merged**
